export type Product = {
  slug: string
  name: string
  tagline: string
  category: 'Healthcare' | 'Hospitality' | 'Operations' | 'Education' | 'Commerce' | 'People'
  icon: string
  accent: string
  summary: string
  modules: string[]
  outcomes: string[]
  idealFor: string
  demoUrl?: string
}

export const QUOTE_FEE_USD = 5

export const products: Product[] = [
  {
    slug: 'hospital-erp',
    name: 'MediCore Hospital ERP',
    tagline: 'One live record from reception to discharge.',
    category: 'Healthcare',
    icon: 'HeartPulse',
    accent: '#22d3ee',
    summary: 'Full hospital management: OPD, IPD, bed mapping, pharmacy, labs, OT, billing, TPA and ABHA-ready patient records, already running at AWT Hospital.',
    modules: ['Reception & queue', 'OPD & EMR', 'IPD & bed mapping', 'Pharmacy', 'Lab & radiology', 'Operation theatre', 'Billing & TPA', 'Inventory & assets', 'MIS reports'],
    outcomes: ['Single patient identity across departments', 'Faster discharge billing', 'Real-time bed occupancy'],
    idealFor: 'Multi-speciality hospitals, nursing homes and day-care centres',
    demoUrl: '/awt-hospital-demo',
  },
  {
    slug: 'clinic-suite',
    name: 'ClinicFlow',
    tagline: 'Appointments, prescriptions and payments for busy clinics.',
    category: 'Healthcare',
    icon: 'Stethoscope',
    accent: '#38bdf8',
    summary: 'A lightweight practice management system with online booking, digital prescriptions, patient history and WhatsApp reminders.',
    modules: ['Online booking', 'Digital Rx', 'Patient history', 'Reminders', 'Billing'],
    outcomes: ['Fewer no-shows', 'Paperless consultations', 'Same-day revenue view'],
    idealFor: 'Single and multi-doctor clinics, dental and eye centres',
  },
  {
    slug: 'diagnostic-lims',
    name: 'LabSync LIMS',
    tagline: 'Sample to signed report, tracked end to end.',
    category: 'Healthcare',
    icon: 'FlaskConical',
    accent: '#2dd4bf',
    summary: 'Laboratory information system with barcode sample tracking, analyser integration, report approval and patient report delivery.',
    modules: ['Barcode samples', 'Analyser interface', 'Report approval', 'Home collection', 'Patient portal'],
    outcomes: ['Lower turnaround time', 'Fewer transcription errors', 'Reports delivered online'],
    idealFor: 'Pathology labs and diagnostic chains',
  },
  {
    slug: 'pharmacy-pos',
    name: 'PharmaDesk',
    tagline: 'Batch-aware pharmacy billing and stock.',
    category: 'Healthcare',
    icon: 'Pill',
    accent: '#34d399',
    summary: 'Pharmacy POS with batch and expiry tracking, GST invoicing, supplier purchase orders and reorder alerts.',
    modules: ['POS billing', 'Batch & expiry', 'Purchase orders', 'GST reports', 'Reorder alerts'],
    outcomes: ['Less expired stock', 'Quicker counter billing', 'Clean GST filing'],
    idealFor: 'Retail pharmacies and hospital dispensaries',
  },
  {
    slug: 'hotel-erp',
    name: 'StayGrid Hotel ERP',
    tagline: 'Front desk, housekeeping and revenue in one view.',
    category: 'Hospitality',
    icon: 'Hotel',
    accent: '#f59e0b',
    summary: 'Property management for hotels and resorts with reservations, channel manager sync, housekeeping, POS and night audit.',
    modules: ['Reservations', 'Front desk', 'Channel manager', 'Housekeeping', 'Night audit', 'Guest folio'],
    outcomes: ['No double bookings', 'Faster check-in', 'Daily revenue clarity'],
    idealFor: 'Hotels, resorts, homestays and serviced apartments',
  },
  {
    slug: 'restaurant-pos',
    name: 'TableTap POS',
    tagline: 'QR ordering, KOT and kitchen display.',
    category: 'Hospitality',
    icon: 'UtensilsCrossed',
    accent: '#fb923c',
    summary: 'Restaurant point of sale with QR table ordering, kitchen display, recipe costing and online aggregator orders.',
    modules: ['QR menu & ordering', 'KOT & KDS', 'Recipe costing', 'Aggregator sync', 'Loyalty'],
    outcomes: ['Shorter table turns', 'Controlled food cost', 'One screen for all orders'],
    idealFor: 'Restaurants, cafés, cloud kitchens and food courts',
  },
  {
    slug: 'manufacturing-erp',
    name: 'ForgeOS Manufacturing ERP',
    tagline: 'Plan, produce and ship with live shop-floor data.',
    category: 'Operations',
    icon: 'Factory',
    accent: '#a78bfa',
    summary: 'ERP for manufacturers covering BOM, production planning, work orders, quality checks, inventory and dispatch.',
    modules: ['BOM & routing', 'Production planning', 'Work orders', 'Quality control', 'Inventory', 'Dispatch'],
    outcomes: ['Accurate material planning', 'Visible WIP', 'On-time dispatch'],
    idealFor: 'Small and mid-size manufacturers',
  },
  {
    slug: 'inventory-wms',
    name: 'StockPilot WMS',
    tagline: 'Know where every unit is, in every warehouse.',
    category: 'Operations',
    icon: 'Warehouse',
    accent: '#818cf8',
    summary: 'Warehouse and inventory management with bin locations, barcode picking, multi-warehouse transfers and stock valuation.',
    modules: ['Bin locations', 'Barcode picking', 'Transfers', 'Cycle counts', 'Valuation'],
    outcomes: ['Fewer picking errors', 'Real-time stock', 'Faster audits'],
    idealFor: 'Distributors, wholesalers and D2C brands',
  },
  {
    slug: 'fleet-logistics',
    name: 'RouteWise Fleet',
    tagline: 'Live tracking, trips and fuel control.',
    category: 'Operations',
    icon: 'Truck',
    accent: '#60a5fa',
    summary: 'Fleet and logistics software with GPS tracking, trip sheets, driver app, proof of delivery and fuel and maintenance logs.',
    modules: ['GPS tracking', 'Trip planning', 'Driver app', 'Proof of delivery', 'Fuel & maintenance'],
    outcomes: ['Lower fuel cost', 'On-time deliveries', 'Paperless POD'],
    idealFor: 'Transporters, courier and last-mile teams',
  },
  {
    slug: 'school-erp',
    name: 'CampusOne School ERP',
    tagline: 'Admissions to report cards, with a parent app.',
    category: 'Education',
    icon: 'GraduationCap',
    accent: '#f472b6',
    summary: 'School management with admissions, fee collection, attendance, timetable, exams and a parent and teacher mobile app.',
    modules: ['Admissions', 'Online fees', 'Attendance', 'Timetable', 'Exams & report cards', 'Parent app'],
    outcomes: ['Fees collected on time', 'Less admin paperwork', 'Engaged parents'],
    idealFor: 'Schools, colleges and coaching groups',
  },
  {
    slug: 'lms',
    name: 'LearnLoop LMS',
    tagline: 'Sell and deliver courses under your own brand.',
    category: 'Education',
    icon: 'BookOpen',
    accent: '#e879f9',
    summary: 'Learning platform with video courses, live classes, quizzes, certificates and built-in course payments.',
    modules: ['Video courses', 'Live classes', 'Quizzes', 'Certificates', 'Payments'],
    outcomes: ['New online revenue', 'Trackable learner progress', 'Branded experience'],
    idealFor: 'Educators, academies and corporate training teams',
  },
  {
    slug: 'retail-pos',
    name: 'ShopSphere Retail POS',
    tagline: 'Billing, stock and loyalty for every store.',
    category: 'Commerce',
    icon: 'ShoppingBag',
    accent: '#facc15',
    summary: 'Retail POS with barcode billing, multi-store stock, customer loyalty, offers and an online store sync.',
    modules: ['Barcode billing', 'Multi-store', 'Loyalty & offers', 'E-store sync', 'Analytics'],
    outcomes: ['Faster checkout', 'Repeat customers', 'Store-wise profitability'],
    idealFor: 'Retail chains, supermarkets and fashion stores',
  },
  {
    slug: 'crm',
    name: 'PipeLine CRM',
    tagline: 'Every lead followed up, automatically.',
    category: 'Commerce',
    icon: 'Target',
    accent: '#fbbf24',
    summary: 'Sales CRM with lead capture from web and WhatsApp, pipelines, automated follow-ups, quotations and AI call summaries.',
    modules: ['Lead capture', 'Pipelines', 'Automations', 'Quotations', 'AI summaries'],
    outcomes: ['Higher conversion', 'No lead left behind', 'Forecast you can trust'],
    idealFor: 'Sales teams, agencies and service businesses',
  },
  {
    slug: 'accounting',
    name: 'LedgerLite Accounting',
    tagline: 'GST-ready books without the spreadsheet chaos.',
    category: 'Commerce',
    icon: 'Calculator',
    accent: '#a3e635',
    summary: 'Cloud accounting with invoicing, expenses, bank reconciliation, GST returns and real-time profit and loss.',
    modules: ['Invoicing', 'Expenses', 'Bank reconciliation', 'GST returns', 'Financial reports'],
    outcomes: ['Books always up to date', 'Faster tax filing', 'Cash flow visibility'],
    idealFor: 'SMEs, startups and accountants',
  },
  {
    slug: 'hrms',
    name: 'PeopleHub HRMS',
    tagline: 'Attendance, payroll and people in one place.',
    category: 'People',
    icon: 'Users',
    accent: '#fb7185',
    summary: 'HR and payroll with geo attendance, leave, payroll with statutory compliance, appraisals and an employee self-service app.',
    modules: ['Geo attendance', 'Leave', 'Payroll & compliance', 'Appraisals', 'Employee app'],
    outcomes: ['Error-free payroll', 'Self-service employees', 'Compliance on autopilot'],
    idealFor: 'Companies with 10 to 5,000 employees',
  },
  {
    slug: 'real-estate',
    name: 'EstateDesk',
    tagline: 'Inventory, bookings and collections for builders.',
    category: 'Commerce',
    icon: 'Building2',
    accent: '#c084fc',
    summary: 'Real estate CRM and ERP with unit inventory, site visits, bookings, payment schedules and a buyer portal.',
    modules: ['Unit inventory', 'Site visits', 'Bookings', 'Payment schedules', 'Buyer portal'],
    outcomes: ['Live unit availability', 'On-time collections', 'Transparent buyers'],
    idealFor: 'Builders, developers and brokers',
  },
  {
    slug: 'gym-management',
    name: 'FitPulse',
    tagline: 'Memberships, check-ins and trainers, sorted.',
    category: 'People',
    icon: 'Dumbbell',
    accent: '#4ade80',
    summary: 'Gym and studio management with memberships, QR check-in, class booking, trainer schedules and renewal reminders.',
    modules: ['Memberships', 'QR check-in', 'Class booking', 'Trainer schedules', 'Renewals'],
    outcomes: ['More renewals', 'Smooth front desk', 'Full classes'],
    idealFor: 'Gyms, yoga studios and fitness chains',
  },
  {
    slug: 'ai-assistant',
    name: 'Byte AI Agents',
    tagline: 'Claude-powered assistants trained on your business.',
    category: 'Operations',
    icon: 'Bot',
    accent: '#2d7cf6',
    summary: 'Custom AI agents for customer support, document processing and internal knowledge, connected to your existing tools.',
    modules: ['Support chatbot', 'Document AI', 'Knowledge search', 'Workflow automation', 'Analytics'],
    outcomes: ['24/7 customer answers', 'Hours saved every week', 'Faster decisions'],
    idealFor: 'Any business that wants to put AI to work',
  },
]

export const categories = ['All', ...Array.from(new Set(products.map((p) => p.category)))] as const

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug)
}
